project_name = "项目代码库理解"
project_id = "xtd"
description = ''
workspace_path = "workspace/xtd"
llm_config = "docs/OAI_CONFIG_LIST.json"

codebase = '/home/jiangbo/gptq'

[[flows]]
flow_name = "代码库理解"
flow_id = "flow1"
config = "workflows/comprehension/flow1_codebase_comprehension/flow_codebase_comprehension.toml"
previous_flows = []
